In [1]:

import pandas as pd
import numpy as np
import model_evaluation_utils as meu
from sklearn.model_selection import train_test_split
import LoggerYN as YN

import time

import datetime

import pandas as pd
import numpy as np
from sklearn.model_selection import *
from sklearn.linear_model import *
from sklearn.preprocessing import *
from sklearn.metrics import *
import sklearn
from sklearn import linear_model
from sklearn import tree 
from sklearn import ensemble


# In[5]:

In [2]:
df = pd.read_csv('AirlinesCodrnaAdult.csv', sep=None,engine='python', header=0)

In [3]:
df.head(10)

,Airline,Flight,AirportFrom,AirportTo,DayOfWeek,Time,Length,codrna_X1,codrna_X2,codrna_X3,...,marital-status,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native-country,Delay
0,US,1558,PHX,CLT,3,15,222,0.698608,0.136363,0.281746,...,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,1
1,AA,2400,LAX,DFW,3,20,165,0.698608,0.136363,0.281746,...,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,1
2,AA,2466,SFO,DFW,3,20,195,0.698608,0.136363,0.281746,...,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,1
3,AS,108,ANC,SEA,3,30,202,0.698608,0.136363,0.281746,...,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,0
4,CO,1094,LAX,IAH,3,30,181,0.698608,0.136363,0.281746,...,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,1
5,DL,1768,LAX,MSP,3,30,220,0.698608,0.136363,0.281746,...,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,0
6,DL,2722,PHX,DTW,3,30,228,0.698608,0.136363,0.281746,...,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,0
7,DL,2606,SFO,MSP,3,35,216,0.698608,0.136363,0.281746,...,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,1
8,AA,2538,LAS,ORD,3,40,200,0.698608,0.136363,0.281746,...,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,1
9,CO,223,ANC,SEA,3,49,201,0.698608,0.136363,0.281746,...,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,1

In [4]:
df.Delay.value_counts()

1    603138
0    473652
Name: Delay, dtype: int64

In [5]:
for column in (df.select_dtypes(include=['object']).columns):
    df[column] = df[column].astype('category').cat.codes

In [6]:
df.dtypes

Airline              int8
Flight              int64
AirportFrom         int16
AirportTo           int16
DayOfWeek           int64
Time                int64
Length              int64
codrna_X1         float64
codrna_X2         float64
codrna_X3         float64
codrna_X4         float64
codrna_X5         float64
codrna_X6         float64
codrna_X7         float64
codrna_X8         float64
age                 int64
workclass            int8
fnlwgt              int64
education            int8
education-num       int64
marital-status       int8
occupation           int8
relationship         int8
race                 int8
sex                  int8
capitalgain         int64
capitalloss         int64
hoursperweek        int64
native-country       int8
Delay               int64
dtype: object

In [7]:
df = df[["Airline","Flight","AirportFrom","AirportTo","DayOfWeek","Time","Length","Delay"]]

In [8]:
X = df.drop('Delay',axis=1)
y = df.pop('Delay')


X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.80,random_state=0)

In [9]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
import xgboost as xgb
from sklearn.svm import SVC


DT = DecisionTreeClassifier()
LR = LogisticRegression(max_iter=1000000,n_jobs=-1)
RF = RandomForestClassifier(n_jobs=-1)
XGB = xgb.XGBClassifier(n_jobs=-1)
KNN = KNeighborsClassifier(n_jobs=-1)
class_labels = list(set(y))

In [9]:

# # Linear Model

memT,cpuT,gpuT = YN.StartLogger("Dataset_M_Instance_S","LinearModel_DT")
start = time.time()
DT.fit(X_train,y_train)
predictions = DT.predict(X_test)
print(meu.display_model_performance_metrics(true_labels=y_test, predicted_labels=predictions, classes=class_labels))
end = time.time()
YN.EndLogger(memT,cpuT,gpuT)
print("total time Linear Model Decision Tree DT ", str(datetime.timedelta(seconds=end-start)))

# # Linear Model

memT,cpuT,gpuT = YN.StartLogger("Dataset_M_Instance_S","LinearModel_LR")
start = time.time()
LR.fit(X_train,y_train)
predictions = LR.predict(X_test)
print(meu.display_model_performance_metrics(true_labels=y_test, predicted_labels=predictions, classes=class_labels))
end = time.time()
YN.EndLogger(memT,cpuT,gpuT)
print("total time Linear Model Logistic Regression", str(datetime.timedelta(seconds=end-start)))

Model Performance metrics:
------------------------------
Accuracy: 0.7807
Precision: 0.7836
Recall: 0.7807
F1 Score: 0.7813

Model Classification report:
------------------------------
              precision    recall  f1-score   support

           0       0.73      0.79      0.76     94841
           1       0.82      0.77      0.80    120517

    accuracy                           0.78    215358
   macro avg       0.78      0.78      0.78    215358
weighted avg       0.78      0.78      0.78    215358

None
total time Linear Model Decision Tree DT  0:00:11.585948
Model Performance metrics:
------------------------------
Accuracy: 0.6242
Precision: 0.6198
Recall: 0.6242
F1 Score: 0.6175

Model Classification report:
------------------------------
              precision    recall  f1-score   support

           0       0.59      0.48      0.53     94841
           1       0.64      0.74      0.69    120517

    accuracy                           0.62    215358
   macro avg       0.62      0.61      0.61    215358
weighted avg       0.62      0.62      0.62    215358

None
total time Linear Model Logistic Regression 0:00:17.532286

In [10]:
memT,cpuT,gpuT = YN.StartLogger("Dataset_M_Instance_S","LinearModel_KNN")
start = time.time()
KNN.fit(X_train,y_train)
predictions = KNN.predict(X_test)
print(meu.display_model_performance_metrics(true_labels=y_test, predicted_labels=predictions, classes=class_labels))
end = time.time()
YN.EndLogger(memT,cpuT,gpuT)
print("total time Linear Model KNN", str(datetime.timedelta(seconds=end-start)))

Model Performance metrics:
------------------------------
Accuracy: 0.7825
Precision: 0.7831
Recall: 0.7825
F1 Score: 0.7827

Model Classification report:
------------------------------
              precision    recall  f1-score   support

           0       0.75      0.76      0.76     94841
           1       0.81      0.80      0.80    120517

    accuracy                           0.78    215358
   macro avg       0.78      0.78      0.78    215358
weighted avg       0.78      0.78      0.78    215358

None
total time Linear Model KNN 1:08:26.347646

In [11]:
# In[18]:
start = time.time()
memT,cpuT,gpuT = YN.StartLogger("Dataset_M_Instance_S","Non-LinearModel_RF")
RF.fit(X_train,y_train)
predictions = RF.predict(X_test)
print(meu.display_model_performance_metrics(true_labels=y_test, predicted_labels=predictions, classes=class_labels))
end = time.time()
YN.EndLogger(memT,cpuT,gpuT)
print("total time Non-Linear Model RF", str(datetime.timedelta(seconds=end-start)))

Model Performance metrics:
------------------------------
Accuracy: 0.6466
Precision: 0.6481
Recall: 0.6466
F1 Score: 0.6301

Model Classification report:
------------------------------
              precision    recall  f1-score   support

           0       0.65      0.42      0.51     94841
           1       0.64      0.82      0.72    120517

    accuracy                           0.65    215358
   macro avg       0.65      0.62      0.62    215358
weighted avg       0.65      0.65      0.63    215358

None
total time Non-Linear Model RF 0:01:35.173056

In [10]:
start = time.time()
memT,cpuT,_ = YN.StartLogger("Dataset_M_Instance_S","Non-LinearModel_XGB")
XGB.fit(X_train,y_train)
predictions = XGB.predict(X_test)
print(meu.display_model_performance_metrics(true_labels=y_test, predicted_labels=predictions, classes=class_labels))
end = time.time()
YN.EndLogger(memT,cpuT,_)
print("total time Non-Linear Model XGB", str(datetime.timedelta(seconds=end-start)))

Model Performance metrics:
------------------------------
Accuracy: 0.6695
Precision: 0.6689
Recall: 0.6695
F1 Score: 0.6608

Model Classification report:
------------------------------
              precision    recall  f1-score   support

           0       0.67      0.50      0.57     94841
           1       0.67      0.80      0.73    120517

    accuracy                           0.67    215358
   macro avg       0.67      0.65      0.65    215358
weighted avg       0.67      0.67      0.66    215358

None
total time Non-Linear Model XGB 0:01:03.514787

In [ ]:
print(meu.display_model_performance_metrics(true_labels=y_test, predicted_labels=predictions, classes=class_labels))